[package]
name = "proto"
version = "0.1.0"
authors = ["gavadinov <gavadinov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.1.0-beta.1"
tonic-build = "0.1.0-beta.1"
